Add version command
dxw/dalmatian-tools pull request #310
Opened 2024-07-02 14:48 UTC by Stretch96

* The commands available in dalmatian-tools, only work with the dalmatian infrastructures launched from the dxw/dalmatian repo (which is private and for internal use only) - we call this dalmatian v1
* There are also commands which only work with the infrastructures deployed via dalmatian-tools - which we call v2
* This change refactors the structure of the commands available in dalmatian tools. The subcommand directories now contain a v1 and/or v2 directory, where the relevant script can be placed. This allows us to have commands named the same, but can be used on either version
* The version command can be used to show the current version, or to switch between them. When on v1, only v1 commands will be available. Which on v2, only v2 commands will be available. If they are needed on both, a symlink can be created between them

2024-07-02 14:49 UTC, DrizzlyOwl commented
I like this idea a lot :)

2024-07-02 15:12 UTC, rjw1 commented
Since I care this seems to have really broken tab completion.

2024-07-02 15:13 UTC, rjw1 requested changes

2024-07-02 15:13 UTC, rjw1 commented on bin/configure-commands/v2/version
> +  log_info -l "switch to 'v1' by running 'dalmatian version -v 2'" -q "$QUIET_MODE"
```suggestion
  log_info -l "switch to 'v1' by running 'dalmatian version -v 1'" -q "$QUIET_MODE"
```

2024-07-02 15:28 UTC, rjw1 commented
@Stretch96 im happy with the completion stuff now :)

2024-07-04 16:17 UTC, rjw1 approved these changes

2024-07-04 16:18 UTC, merged