Add commands to allow setting service environment variables
dxw/dalmatian-tools pull request #325
Opened 2024-07-16 15:00 UTC by Stretch96

- `service list-services`
    - This lists the services within an Infarstructures ECS cluster
    - It provides useful information about the services running on the
      cluster, in JSON format so that it can easily be used by other
      commands
- `service deploy`
    - This command runs the codepipeline for a given service, to redeploy it
- `service set-environment-variables`
    - This checks for and temporarily copies a .env file for a given service
      (if it doesn't exist, a new one can be optionally created)
    - The user is then prompted to redeploy the service

2024-07-16 15:43 UTC, rjw1 requested changes
As well as my comment about the upload and deploy stuff. YOu typoed the name of the set-environment-file.

2024-07-16 15:43 UTC, rjw1 commented on bin/service/v2/set-envinoment-variables
> +
i wonder if it should check that there has actually been a change. show a diff and then ask for confirmation of the upload.

2024-07-16 15:43 UTC, rjw1 commented on bin/service/v2/set-envinoment-variables
> +
or not uplaod at all if there is no diff.

2024-07-17 11:16 UTC, rjw1 requested changes

2024-07-17 11:16 UTC, rjw1 commented on bin/service/v2/set-environment-variables
> +DIFF="$(diff "$LOCAL_ENVIRONMENT_FILE-orig" "$LOCAL_ENVIRONMENT_FILE" || true)"
So I prefer the output from `diff -u` and indeed since we have a brewfile and can add `colordiff` we can  then do `colordiff -u` so things look like a nice `git diff` 

This could also be done with `git diff --no-index file1 file2`

2024-07-18 15:06 UTC, Stretch96 commented on bin/service/v2/set-environment-variables
> +DIFF="$(diff "$LOCAL_ENVIRONMENT_FILE-orig" "$LOCAL_ENVIRONMENT_FILE" || true)"
I've added colordiff in now 👍

2024-07-19 09:52 UTC, rjw1 approved these changes
Fix the environemnt typo but other wise ship it :)

2024-07-19 09:52 UTC, rjw1 commented on bin/service/v2/set-environment-variables
> +if yes_no "Envinroment file updated, do you want to redeploy the service now?" "y"
```suggestion
if yes_no "Environment file updated, do you want to redeploy the service now?" "y"
```

2024-07-19 09:59 UTC, merged